mod launcher;

use super::common::{
    parse_json_object, serialize_json_pretty, should_restore_standard_relay_config, write_text_file,
};
use crate::theme::AgentConfig;
use serde_json::json;
use std::path::PathBuf;

fn deepseek_settings_path() -> PathBuf {
    crate::paths::pad_home_dir()
        .join("deepseek-config")
        .join("settings.json")
}

pub(super) fn apply_deepseek_agent_config(agent: &AgentConfig) {
    let path = deepseek_settings_path();

    if should_restore_standard_relay_config(agent) {
        let _ = std::fs::remove_file(&path);
        remove_deepseek_launcher_script();
        return;
    }

    let Some(prov) = agent.active() else {
        let _ = std::fs::remove_file(&path);
        remove_deepseek_launcher_script();
        return;
    };

    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }

    let content = std::fs::read_to_string(&path).unwrap_or_else(|_| "{}".to_string());

    let updated = update_deepseek_settings_config(
        &content,
        &prov.base_url,
        &prov.api_key,
        &agent.default_model,
        prov.disable_thinking,
    );
    write_text_file(&path, &updated);

    generate_deepseek_launcher_script(&prov.base_url, &prov.api_key, &agent.default_model);
}

fn update_deepseek_settings_config(
    content: &str,
    base_url: &str,
    api_key: &str,
    default_model: &str,
    disable_thinking: bool,
) -> String {
    let mut obj = parse_json_object(content);
    obj.as_object_mut()
        .expect("deepseek settings root")
        .remove("apiUrl");
    obj.as_object_mut()
        .expect("deepseek settings root")
        .remove("apiKey");

    let env = obj
        .as_object_mut()
        .expect("deepseek settings root")
        .entry("env".to_string())
        .or_insert_with(|| json!({}));
    if !env.is_object() {
        *env = json!({});
    }

    let env_obj = env.as_object_mut().expect("deepseek env object");
    env_obj.insert(
        "ANTHROPIC_BASE_URL".to_string(),
        serde_json::Value::String(normalize_base_url(base_url)),
    );
    env_obj.insert(
        "ANTHROPIC_AUTH_TOKEN".to_string(),
        serde_json::Value::String(api_key.to_string()),
    );
    env_obj.remove("ANTHROPIC_API_KEY");
    env_obj.insert(
        "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC".to_string(),
        serde_json::Value::String("1".to_string()),
    );
    env_obj.insert(
        "CLAUDE_CODE_ATTRIBUTION_HEADER".to_string(),
        serde_json::Value::String("0".to_string()),
    );
    env_obj.remove("CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS");
    env_obj.remove("MAX_THINKING_TOKENS");
    if disable_thinking {
        env_obj.insert(
            "CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS".to_string(),
            serde_json::Value::String("1".to_string()),
        );
        env_obj.insert(
            "MAX_THINKING_TOKENS".to_string(),
            serde_json::Value::String("0".to_string()),
        );
    }
    env_obj.remove("ANTHROPIC_MODEL");
    env_obj.remove("ANTHROPIC_CUSTOM_MODEL_OPTION");
    if !default_model.trim().is_empty() {
        env_obj.insert(
            "ANTHROPIC_MODEL".to_string(),
            serde_json::Value::String(default_model.trim().to_string()),
        );
        env_obj.insert(
            "ANTHROPIC_CUSTOM_MODEL_OPTION".to_string(),
            serde_json::Value::String(default_model.trim().to_string()),
        );
    }

    serialize_json_pretty(&obj)
}

fn normalize_base_url(raw: &str) -> String {
    let trimmed = raw.trim().trim_end_matches('/');
    if trimmed == "https://api.deepseek.com" {
        return "https://api.deepseek.com/anthropic".to_string();
    }
    trimmed.strip_suffix("/v1").unwrap_or(trimmed).to_string()
}

fn deepseek_launcher_script_path() -> PathBuf {
    crate::paths::pad_home_dir().join("deepseek-cc")
}

fn generate_deepseek_launcher_script(base_url: &str, api_key: &str, model: &str) {
    let script_path = deepseek_launcher_script_path();
    let normalized_url = normalize_base_url(base_url);
    let model_name = if model.trim().is_empty() {
        "deepseek-v4-flash"
    } else {
        model.trim()
    };

    let deepseek_config_dir = crate::paths::pad_home_dir().join("deepseek-config");
    let script = format!(
        r#"#!/bin/bash
# DeepSeek(cc) launcher - Auto-generated by pad
export CLAUDE_CONFIG_DIR="{}"
export ANTHROPIC_BASE_URL="{}"
export ANTHROPIC_AUTH_TOKEN="{}"
export ANTHROPIC_MODEL="{}"
exec claude "$@"
"#,
        deepseek_config_dir.display(),
        normalized_url,
        api_key,
        model_name
    );

    if let Err(e) = launcher::write(&script_path, script.as_bytes()) {
        eprintln!("Failed to write deepseek launcher: {}", e);
    }
}

fn remove_deepseek_launcher_script() {
    let script_path = deepseek_launcher_script_path();
    let _ = std::fs::remove_file(script_path);
}
