use std::fmt;

#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct PaneId(String);

impl PaneId {
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for PaneId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TerminalSize {
    pub columns: u16,
    pub rows: u16,
}

impl TerminalSize {
    pub fn new(columns: u16, rows: u16) -> Self {
        Self {
            columns: columns.max(1),
            rows: rows.max(1),
        }
    }

    pub fn cell_count(self) -> usize {
        usize::from(self.columns) * usize::from(self.rows)
    }
}

/// Side effects emitted by a terminal parser which must be handled outside
/// the terminal grid.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TerminalEngineEvent {
    /// Bytes generated by terminal queries which must be written back to the
    /// attached PTY in order.
    PtyWrite(Vec<u8>),
    /// Set the pane title, or reset it to the transport's default with `None`.
    Title(Option<String>),
    Bell,
    Exit,
    /// A request intentionally left to a future integration. Keeping this as
    /// an event makes the limitation observable without fabricating a reply.
    UnsupportedRequest(String),
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum TerminalColor {
    #[default]
    DefaultForeground,
    DefaultBackground,
    Indexed(u8),
    Named(u16),
    Rgb(u8, u8, u8),
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct TextAttributes {
    pub bold: bool,
    pub dim: bool,
    pub italic: bool,
    pub underline: bool,
    pub inverse: bool,
    pub hidden: bool,
    pub strikeout: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TerminalCell {
    pub symbol: String,
    pub foreground: TerminalColor,
    pub background: TerminalColor,
    pub attributes: TextAttributes,
}

impl Default for TerminalCell {
    fn default() -> Self {
        Self {
            symbol: " ".to_string(),
            foreground: TerminalColor::DefaultForeground,
            background: TerminalColor::DefaultBackground,
            attributes: TextAttributes::default(),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CursorShape {
    Block,
    Underline,
    Beam,
    HollowBlock,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TerminalCursor {
    pub column: u16,
    pub row: u16,
    pub shape: CursorShape,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct TerminalMode {
    pub alternate_screen: bool,
    pub bracketed_paste: bool,
    pub mouse_reporting: bool,
    pub sgr_mouse: bool,
    pub application_cursor: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TerminalSnapshot {
    pub size: TerminalSize,
    pub cells: Vec<TerminalCell>,
    pub cursor: Option<TerminalCursor>,
    pub mode: TerminalMode,
}

impl TerminalSnapshot {
    pub fn blank(size: TerminalSize) -> Self {
        Self {
            size,
            cells: vec![TerminalCell::default(); size.cell_count()],
            cursor: None,
            mode: TerminalMode::default(),
        }
    }

    pub fn cell(&self, column: u16, row: u16) -> Option<&TerminalCell> {
        if column >= self.size.columns || row >= self.size.rows {
            return None;
        }
        let index = usize::from(row) * usize::from(self.size.columns) + usize::from(column);
        self.cells.get(index)
    }

    pub fn row_text(&self, row: u16) -> Option<String> {
        if row >= self.size.rows {
            return None;
        }
        let start = usize::from(row) * usize::from(self.size.columns);
        let end = start + usize::from(self.size.columns);
        let mut text = String::new();
        for cell in self.cells.get(start..end)? {
            text.push_str(&cell.symbol);
        }
        // Empty grid cells are represented by ASCII spaces. Do not use
        // `trim_end`, since it also removes visible Unicode whitespace such as
        // non-breaking spaces written by the application.
        Some(text.trim_end_matches(' ').to_string())
    }
}
