pub(super) fn text(locale: crate::i18n::Locale, key: &str) -> Option<&'static str> {
    Some(match (locale, key) {
        (crate::i18n::Locale::ZhCN, "title") => "Pad Telegram",
        (crate::i18n::Locale::ZhTW, "title") => "Pad Telegram",
        (crate::i18n::Locale::Ja, "title") => "Pad Telegram",
        (crate::i18n::Locale::De, "title") => "Pad Telegram",
        (crate::i18n::Locale::Fr, "title") => "Pad Telegram",
        (_, "title") => "Pad Telegram",
        (crate::i18n::Locale::ZhCN, "target") => "当前目标",
        (crate::i18n::Locale::ZhTW, "target") => "目前目標",
        (crate::i18n::Locale::Ja, "target") => "現在のターゲット",
        (crate::i18n::Locale::De, "target") => "Aktuelles Ziel",
        (crate::i18n::Locale::Fr, "target") => "Cible actuelle",
        (_, "target") => "Current Target",
        (crate::i18n::Locale::ZhCN, "target.none") => "尚未选择",
        (crate::i18n::Locale::ZhTW, "target.none") => "尚未選擇",
        (crate::i18n::Locale::Ja, "target.none") => "未選択",
        (crate::i18n::Locale::De, "target.none") => "nichts ausgewählt",
        (crate::i18n::Locale::Fr, "target.none") => "aucune cible",
        (_, "target.none") => "none selected",
        (crate::i18n::Locale::ZhCN, "section.quick") => "开始使用",
        (crate::i18n::Locale::ZhTW, "section.quick") => "開始使用",
        (crate::i18n::Locale::Ja, "section.quick") => "はじめ方",
        (crate::i18n::Locale::De, "section.quick") => "Loslegen",
        (crate::i18n::Locale::Fr, "section.quick") => "Pour démarrer",
        (_, "section.quick") => "Getting Started",
        (crate::i18n::Locale::ZhCN, "section.utility") => "常用补充",
        (crate::i18n::Locale::ZhTW, "section.utility") => "常用補充",
        (crate::i18n::Locale::Ja, "section.utility") => "補助コマンド",
        (crate::i18n::Locale::De, "section.utility") => "Nützlich",
        (crate::i18n::Locale::Fr, "section.utility") => "Utilitaires",
        (_, "section.utility") => "Useful Extras",
        (crate::i18n::Locale::ZhCN, "section.commands") => "已接入命令",
        (crate::i18n::Locale::ZhTW, "section.commands") => "已接入命令",
        (crate::i18n::Locale::Ja, "section.commands") => "対応済みコマンド",
        (crate::i18n::Locale::De, "section.commands") => "Verfügbare Befehle",
        (crate::i18n::Locale::Fr, "section.commands") => "Commandes disponibles",
        (_, "section.commands") => "Available Commands",
        (crate::i18n::Locale::ZhCN, "section.flow") => "执行阶段",
        (crate::i18n::Locale::ZhTW, "section.flow") => "執行階段",
        (crate::i18n::Locale::Ja, "section.flow") => "実行ステージ",
        (crate::i18n::Locale::De, "section.flow") => "Phasen",
        (crate::i18n::Locale::Fr, "section.flow") => "Étapes",
        (_, "section.flow") => "Stages",
        _ => return None,
    })
}
