pub(super) fn text(locale: crate::i18n::Locale, key: &str) -> Option<&'static str> {
    Some(match (locale, key) {
        (crate::i18n::Locale::ZhCN, "workflow.accepted") => "已提交：prompt 已成功送入目标 pane。",
        (crate::i18n::Locale::ZhTW, "workflow.accepted") => "已提交：prompt 已成功送入目標 pane。",
        (crate::i18n::Locale::Ja, "workflow.accepted") => "Submitted: prompt が対象 pane に正常に投入されました。",
        (crate::i18n::Locale::De, "workflow.accepted") => "Submitted: Der Prompt wurde erfolgreich an das Ziel-Pane gesendet.",
        (crate::i18n::Locale::Fr, "workflow.accepted") => "Submitted : le prompt a bien été injecté dans le pane cible.",
        (_, "workflow.accepted") => "Submitted: the prompt has been injected into the target pane.",
        (crate::i18n::Locale::ZhCN, "workflow.working") => "进行中：bot 会持续显示工作状态。",
        (crate::i18n::Locale::ZhTW, "workflow.working") => "進行中：bot 會持續顯示工作狀態。",
        (crate::i18n::Locale::Ja, "workflow.working") => "Working: bot が作業中ステータスを継続表示します。",
        (crate::i18n::Locale::De, "workflow.working") => "Working: Der Bot zeigt fortlaufend den Arbeitsstatus an.",
        (crate::i18n::Locale::Fr, "workflow.working") => "Working : le bot affiche l'état de travail en continu.",
        (_, "workflow.working") => "Working: the bot keeps showing live status.",
        (crate::i18n::Locale::ZhCN, "workflow.approval") => "等待确认：Codex 需要提权时会弹出审批按钮。",
        (crate::i18n::Locale::ZhTW, "workflow.approval") => "等待確認：Codex 需要提權時會彈出審批按鈕。",
        (crate::i18n::Locale::Ja, "workflow.approval") => "承認待ち: Codex が権限昇格を求めると承認ボタンが表示されます。",
        (crate::i18n::Locale::De, "workflow.approval") => "Freigabe nötig: Wenn Codex erhöhte Rechte braucht, erscheinen Freigabeknöpfe.",
        (crate::i18n::Locale::Fr, "workflow.approval") => "Approbation requise : si Codex demande une élévation, des boutons d'approbation apparaissent.",
        (_, "workflow.approval") => "Needs approval: approval buttons appear when Codex requests escalation.",
        (crate::i18n::Locale::ZhCN, "workflow.completed") => "已完成：Stop hook 到达后回传最终结果。",
        (crate::i18n::Locale::ZhTW, "workflow.completed") => "已完成：Stop hook 到達後回傳最終結果。",
        (crate::i18n::Locale::Ja, "workflow.completed") => "Completed: Stop hook 到着後に最終結果が返送されます。",
        (crate::i18n::Locale::De, "workflow.completed") => "Completed: Nach dem Stop-Hook wird das Endergebnis zurückgesendet.",
        (crate::i18n::Locale::Fr, "workflow.completed") => "Completed : le résultat final est renvoyé après le hook Stop.",
        (_, "workflow.completed") => "Completed: the final result is sent back after the stop hook.",
        (crate::i18n::Locale::ZhCN, "workflow.tip") => "如果长时间卡在 Waiting，先在 pad 里确认当前 pane 是否还在等待审批或用户输入。",
        (crate::i18n::Locale::ZhTW, "workflow.tip") => "如果長時間卡在 Waiting，先在 pad 裡確認目前 pane 是否仍在等待審批或使用者輸入。",
        (crate::i18n::Locale::Ja, "workflow.tip") => "Waiting が長く続く場合は、pad 側でその pane がまだ承認や入力待ちかを先に確認してください。",
        (crate::i18n::Locale::De, "workflow.tip") => "Wenn Waiting lange bestehen bleibt, prüfe zuerst in pad, ob das Pane noch auf Freigabe oder Eingabe wartet.",
        (crate::i18n::Locale::Fr, "workflow.tip") => "Si l'état Waiting dure trop longtemps, vérifiez d'abord dans pad si le pane attend encore une approbation ou une saisie.",
        (_, "workflow.tip") => "If Waiting lasts too long, check in pad whether the pane is still waiting for approval or user input.",
        _ => return None,
    })
}
