#!/usr/bin/env bash
# This file is generated by scripts/build_installer.sh from install/*.sh.
# Do not edit install.sh directly.
set -euo pipefail

REPO="T1mn/pad"
INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/bin}"
VERSION_INPUT="${VERSION:-latest}"
ASSUME_YES="${PAD_INSTALL_ASSUME_YES:-0}"
FORCE_SOURCE="${PAD_INSTALL_FORCE_SOURCE:-0}"
DISABLE_SOURCE_FALLBACK="${PAD_INSTALL_DISABLE_SOURCE_FALLBACK:-0}"
RELEASE_BASE_URL="${PAD_RELEASE_BASE_URL:-https://github.com/${REPO}/releases/download}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd 2>/dev/null || pwd)"
TEMP_DIRS=()

cleanup_temp_dirs() {
  if [ "${#TEMP_DIRS[@]}" -eq 0 ]; then
    return 0
  fi
  local dir
  for dir in "${TEMP_DIRS[@]}"; do
    [ -n "${dir}" ] && rm -rf "${dir}"
  done
}

trap cleanup_temp_dirs EXIT

say() {
  printf "%b\n" "$*"
}

warn() {
  say "${YELLOW}$*${NC}"
}

ok() {
  say "${GREEN}$*${NC}"
}

err() {
  say "${RED}$*${NC}" >&2
}

check_tmux() {
  command -v tmux >/dev/null 2>&1
}

check_rust() {
  command -v cargo >/dev/null 2>&1
}

check_command() {
  command -v "$1" >/dev/null 2>&1
}

require_command() {
  local cmd="$1"
  local hint="${2:-}"
  if check_command "$cmd"; then
    return 0
  fi

  err "✗ Required command not found: ${cmd}"
  if [ -n "$hint" ]; then
    say "  ${hint}"
  fi
  exit 1
}
